### ISSUE TITLE
 System crashes when uploading package without script.py file into execution service

### ISSUE THREAD

**Issue by hanapelikanova** [robofit/arcor2#137] opened 2020-06-10 12:45 UTC
**Steps to reproduce:**

1. Upload execution package which does not contain script.py file into execution service and click on "execute" button.
- Loading symbol is displayed and nothing else happens.
2. Click again on "execute" button or refresh page.
- Server sends Internal Server Error (see attachment).
- Console writes out BrokenPipeError.
- Method Get Packages returns the same error.

To reverse this state, it is necessary to stop docker container and start it again.

[ServerResponse.txt](https://github.com/robofit/arcor2/files/4758471/ServerResponse.txt)

**Comment by ZdenekM** [comment] 2020-06-11 08:25
Thanks for reporting this. The root cause was an unhandled exception in the Execution Service. The fix (https://github.com/robofit/arcor2/commit/3f7a91e3ea43922ec85202a614cdc586b93d33c4) will be included in the next regular release.
Execution proxy (REST API to the Execution Service) does not handle all possible error states so far, there is a new issue for this: https://github.com/robofit/arcor2/issues/139.

**Closed by ZdenekM** 2020-06-11 08:25 UTC
Labels: Execution Service, bug
