### ISSUE TITLE
Cleanup objects and scene

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2#603] opened 2021-06-14 11:36 UTC
Always on resources destroy, script end with error message:

"There is no collision with id xxx".

It is may be caused by objects and scene destroy (cleanup). Scene call delete_all and start delete all collisions but before delete specific object this object destroys self (call delete on self), after that collision already doesn't exist in the scene, but scene call delete on it.

**Comment by ZdenekM** [comment] 2021-06-14 12:02
Thanks for reporting. The issue is fixed in https://github.com/robofit/arcor2/pull/602.

**Closed by ZdenekM** 2021-06-14 12:02 UTC
Labels: arcor2, arcor2_execution, bug
